### PR TITLE
fixed cursor extraction

### PR DESCRIPTION
**Pull request by morus12**
Fixed issues with cursors when using querystring filters. Test included.

### CODE REVIEW

**Comment by cristiangraz** [comment]
Hi @morus12, 

Thanks for the contribution!

I wasn't able to find additional query string parameters mentioned in their documentation for cursors. I did find this example in the official PHP client's fixtures -- showing an additional per_page in the query string (which would break the current regex).

https://github.com/recurly/recurly-client-php/blob/51a876606d537ce7190392b82661dca259b86b90/Tests/fixtures/accounts/index-200.xml#L4

I'm wondering if it makes sense to parse the URL and return ```url.Values``` for the query string (or return them as ```recurly.Params``` so they can be fed directly into the following API call. Would love to hear your thoughts based on your use case. Is just returning the cursor string sufficient, and you populate the other params yourself for the next API call?

**Comment by morus12** [comment]
Hi @cristiangraz,

I've added to tests header from official PHP client's fixtures and it passes. 

We use your lib in a very small project - it's importing refunds from Recurly to Xero (https://www.xero.com/). We populate API params by ourself.

I think it's a good idea to parse query string using url.Values and get rid of regexes.

**Comment by cristiangraz** [comment]
Thanks for the feedback, @morus12. I'm finishing up a time-sensitive project but will work something up for this early next week. Would appreciate some feedback once it's ready.

Thanks!

**Comment by cristiangraz** [comment]
@morus12 Fixed in https://github.com/blacklightcms/go-recurly/commit/d4406c6b8843037f1d50297afb2b3dac63cf5691. Thanks for identifying this bug!

**Pull request closed without merging**
